"""migration 3

Revision ID: eb0e800de86c
Revises: cbbadc10cb6c
Create Date: 2026-07-02 14:34:33.518100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0e800de86c'
down_revision: Union[str, Sequence[str], None] = 'cbbadc10cb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('logs_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('normalized_fields', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('retention_expired', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('logs_id')
    )
    op.create_index(op.f('ix_logs_logs_id'), 'logs', ['logs_id'], unique=False)
    op.create_table('sources',
    sa.Column('sources_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('adress_ip', sa.String(), nullable=True),
    sa.Column('environnement', sa.String(), nullable=True),
    sa.Column('status_collect', sa.String(), nullable=False),
    sa.Column('recept_final', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sources_id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_sources_id'), 'sources', ['sources_id'], unique=False)
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    op.create_table('ueba_profiles',
    sa.Column('ueba_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_ref', sa.String(), nullable=False),
    sa.Column('baseline', sa.String(), nullable=False),
    sa.Column('score_risque_courant', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ueba_id')
    )
    op.create_index(op.f('ix_ueba_profiles_ueba_id'), 'ueba_profiles', ['ueba_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_audit_id'), 'audit_log', ['audit_id'], unique=False)
    op.create_table('correlation_rules',
    sa.Column('correlation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('fenetre_temporelle_s', sa.Integer(), nullable=False),
    sa.Column('mitre_tactic', sa.String(), nullable=True),
    sa.Column('niveau_alerte', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('correlation_id')
    )
    op.create_index(op.f('ix_correlation_rules_correlation_id'), 'correlation_rules', ['correlation_id'], unique=False)
    op.create_table('incidents',
    sa.Column('incidents_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('priorite', sa.String(), nullable=False),
    sa.Column('date_ouverture', sa.Date(), nullable=False),
    sa.Column('date_fermeture', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('incidents_id')
    )
    op.create_index(op.f('ix_incidents_incidents_id'), 'incidents', ['incidents_id'], unique=False)
    op.create_index(op.f('ix_incidents_titre'), 'incidents', ['titre'], unique=False)
    op.create_table('rentention_policies',
    sa.Column('rent_id', sa.Integer(), nullable=False),
    sa.Column('perimetre', sa.String(), nullable=False),
    sa.Column('duree_jour', sa.Integer(), nullable=False),
    sa.Column('action_post_expiration', sa.String(), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['update_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('rent_id')
    )
    op.create_index(op.f('ix_rentention_policies_rent_id'), 'rentention_policies', ['rent_id'], unique=False)
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('genered_by', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('debut', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genered_by'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_report_id'), 'report', ['report_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alerts_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('log_refs', sa.String(), nullable=False),
    sa.Column('niveau', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('score_risque', sa.Integer(), nullable=True),
    sa.Column('commentaire', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlation_rules.correlation_id'], ),
    sa.PrimaryKeyConstraint('alerts_id')
    )
    op.create_index(op.f('ix_alerts_alerts_id'), 'alerts', ['alerts_id'], unique=False)
    op.create_index(op.f('ix_alerts_log_refs'), 'alerts', ['log_refs'], unique=False)
    op.create_table('playbook',
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('triggers_rules_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('validation_requise', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggers_rules_id'], ['correlation_rules.correlation_id'], ),
    sa.PrimaryKeyConstraint('playbook_id')
    )
    op.create_index(op.f('ix_playbook_playbook_id'), 'playbook', ['playbook_id'], unique=False)
    op.create_table('playbook_execution',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('incidents_id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('log_executed', sa.String(), nullable=True),
    sa.Column('execute_date', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.users_id'], ),
    sa.ForeignKeyConstraint(['incidents_id'], ['incidents.incidents_id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbook.playbook_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_playbook_execution_execution_id'), 'playbook_execution', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbook_execution_execution_id'), table_name='playbook_execution')
    op.drop_table('playbook_execution')
    op.drop_index(op.f('ix_playbook_playbook_id'), table_name='playbook')
    op.drop_table('playbook')
    op.drop_index(op.f('ix_alerts_log_refs'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_report_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_rentention_policies_rent_id'), table_name='rentention_policies')
    op.drop_table('rentention_policies')
    op.drop_index(op.f('ix_incidents_titre'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_correlation_rules_correlation_id'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    op.drop_index(op.f('ix_audit_log_audit_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ueba_profiles_ueba_id'), table_name='ueba_profiles')
    op.drop_table('ueba_profiles')
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_logs_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
